### PR TITLE
Add kurdish

### LINKED ISSUE #104: Add Kurdish (Kurdî) to the languages menu

### PR DESCRIPTION
**Pull request by chrisgarrity**
### Resolves

- Resolves #104 

### Proposed Changes

Adds Kurdish to the supported languages.

## Checklist for updating translations

There are two situations in which we create manual PRs to update translations:

1. We don't want to wait for Travis's automatic weekly update; or,
2. We need to add a language that has become ready

### 1. Updating translations manually

* [x] Pull editor translations from Transifex with `> npm run pull:editor`
* [x] Pull www translations from Transifex with `> npm run pull:www`
* [x] Test the result with `> npm run test`
* [x] Confirm that you see changes to files like `editor/<resource>/<lang code>.json`

### Adding a language

* [x] Edit `src/supported-locales.js`:
  * [x] Add entry for the language in the `locales` const
  * [ ] ~Check if language is right-to-left. If so:~
    * Add entry in `rtlLocales`

* [ ] ~Check if the new language uses a country code~
  * Check [https://www.transifex.com/explore/languages](https://www.transifex.com/explore/languages).

* [x] Edit `src/index.js`:
  * [x] Add 'import' line and export line
  * [x] Add entry in `localeData` array

* [x] Check if locale is in `react-intl`
  * Look in [https://unpkg.com/react-intl/locale-data/](https://unpkg.com/react-intl@2.8.0/locale-data/)
  * ~If not in `react-intl`:~

* [x] Update translations per the "Updating translations" section above
* [x] Confirm that we see changes to:
    * [x] `src/supported-locales.js`
    * [x] `src/index.js`
    * [ ] ~`.tx/config` (if language needed a new locale)~
    * [x] Multiple files like `editor/<resource>/<lang code>.json`

* [x] Bump minor version number in `package.json`

* [ ] **Update scratch-blocks dependency**
    * scratch-blocks has its own translations. It will not pick up the new language unless the scratch-l10n dependency in `package.json` is updated to the new minor version.

* [ ] **Add language po files to scratchr2_translations**
    * manually update `scratchr2_translations/legacy` with `tx pull -l <locale>` and check in changes

* [ ] **Add language to scratchr2 settings**
    * manually update `settings/base.py` with the new language

### CODE REVIEW

**Comment by benjiwheeler** [comment]
This is looking good to me -- the checklist really helps!

I'd like to talk a bit about what we should call these varieties of Kurdish language. It sounds like there are conflicting answers about that; e.g., Wikipedia seems to suggest that speakers of Northern Kurdish/Kurmanji call it "Kurmancî‎".

**Comment by chrisgarrity** [comment]
In this case the name for the menu came from the translator who let me know that Kurdish was ready. When a language is ready I usually ask the translators for how it should appear in the menu.

**Comment by chrisgarrity** [comment]
Since I don't think we should change the name from what the translator sent me, and this PR is holding up the other updates I'm going to go ahead and merge.

**Comment by benjiwheeler** [comment]
FYI -- I spoke to a friend of a friend who is Kurdish. I wanted to get a sense of what people call the language from within it, and if there are political elements to shy away from. He said calling the language “Kurdi” in its own extended Latin script sounded fine. He thought all speakers of varieties of Kurdish would first look for “K” in their language script, and then see the Arabic and Latin script variants and know which one was for them.

So I agree, let’s just go with it!

**Pull request merged**
